mongodb:
  image: mongo:latest
  container_name: mongodb
  command: mongod --smallfiles
  ports:
   - "27017:27017"
  volumes:
   - ./mongo:/data/db:rw
  volume_driver: local
hygieia-api:
  image: hygieia-api
  container_name: hygieia-api
  ports:
  - "8080:8080"
  volumes:
  - ./logs:/hygieia/logs
  links:
  - mongodb:mongo
hygieia-ui:
  image: hygieia-ui
  container_name: hygieia-ui
  ports:
  - "80:80"
  links:
  - hygieia-api
mongo-express:
  image: knickers/mongo-express
  container_name: mongo-express
  ports:
  - "8081:8081"
  links:
  - mongodb:mongo
